"""empty message

Revision ID: 1cd4c4177403
Revises: 0ca88ac43663
Create Date: 2023-08-14 15:53:20.420421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd4c4177403'
down_revision = '0ca88ac43663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['id_user'], ['id'])

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_description_key', type_='unique')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_description_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('planets_description_key', ['description'])

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_unique_constraint('people_description_key', ['description'])

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###
