"""empty message

Revision ID: fff867a432d8
Revises: 65d3b6343d00
Create Date: 2023-08-15 02:05:38.232570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff867a432d8'
down_revision = '65d3b6343d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('id_people',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_planets',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('id_planets',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_people',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
